version: '3.8'

services:

  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - loadbalancer

  calc:
    build: ./calc
    container_name: calc
    ports:
      - "9090:9090"
    depends_on:
      - server
